namespace System.Web
{
	internal enum StateServicePerfCounter
	{
		STATE_SERVICE_SESSIONS_ACTIVE = 97,
		STATE_SERVICE_SESSIONS_ABANDONED = 98,
		STATE_SERVICE_SESSIONS_TIMED_OUT = 99,
		STATE_SERVICE_SESSIONS_TOTAL = 100,
	}
}
